filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  index: "EventualShop-%{+yyyy.MM.dd}"
 
setup.kibana:
  host: "http://kibana:5601"
  
setup.template.name: "EventualShop"
setup.template.pattern: "EventualShop-*"

logging.level: info