name: Codacy Quality Gate

on:
  workflow_call:
    inputs:
      path:
        description: 'The path of project passed from the caller workflow'
        required: true
        type: string

permissions:
  contents: read

jobs:
  codacy-quality-gate:
    name: Codacy Quality Gate
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          directory: ${{ inputs.path }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif