on:
  workflow_call:
    inputs:
      path:
        description: 'The path of project passed from the caller workflow'
        required: true
        type: string

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Run Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          directory: ${{ inputs.path }}/WorkerService
          verbose: false
          output: results.sarif
          format: sarif
          tool: sonarscharp
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Get results
        id: vars
        run: echo ::set-output name=result::$(cat results.sarif)
      - name: Test output
        run: echo ${{ steps.vars.outputs.result }}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif