name: Account

on:
  push:
    paths:
      - src/Services/Account/**.cs
      - src/Services/Account/**.csproj
      - Directory.Build.props
      - .github/workflows/account.yaml

jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/Account
      project: WorkerService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests