name: Catalog

on:
  push:
    paths:
      - src/Services/Catalog/**.cs
      - src/Services/Catalog/**.csproj
      - Directory.Build.props
      - .github/workflows/**

jobs:
  catalog-build-and-test:
    uses: ./.github/workflows/_build-and-test.yaml
    with:
      project: ./src/Services/Catalog/WorkerService
      test: ./test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests
  
  catalog-codacy:
    uses: ./.github/workflows/_codacy.yaml
    with:
      path: /src/Services/Catalog
  
  catalog-codeql:
    uses: ./.github/workflows/_codeql.yaml
    with:
      path: ./src/Services/Catalog