name: Catalog

on:
  push:
    paths:
      - src/Services/Catalog/**.cs
      - src/Services/Catalog/**.csproj
      - Directory.Build.props
      - .github/workflows/catalog.yaml

jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      project: src/Services/Catalog
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests