name: Catalog - Query
run-name: Catalog Query Workflow
on:
  push:
    paths:
      - src/Services/Catalog/Query/**.cs
      - src/Services/Catalog/Query/**.csproj
      - Directory.Build.props
      - .github/workflows/catalog-query.yaml
jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/Catalog/Query
      project: GrpcService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests