name: Identity - Command Stack

on:
  push:
    paths:
      - src/Services/Identity/Command/**.cs
      - src/Services/Identity/Command/**.csproj
      - Directory.Build.props
      - .github/workflows/identity-command.yaml

jobs:
  workflow:
    uses: ./.github/workflows/Templates/_workflow.yaml
    with:
      path: src/Services/Identity/Command
      project: WorkerService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests  