name: Identity Codacy

on:
  push:
    paths:
      - src/Services/Identity/**.cs
      - src/Services/Identity/**.csproj
      - Directory.Build.props

jobs:
  identity-codacy:
    uses: ./.github/workflows/codacy.yaml
    with:
      path: ./src/Services/Identity