name: Payment - Query
run-name: Payment Query Workflow
on:
  push:
    paths:
      - src/Services/Payment/Query/**.cs
      - src/Services/Payment/Query/**.csproj
      - Directory.Build.props
      - .github/workflows/payment-query.yaml
jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/Payment/Query
      project: GrpcService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests