name: Payment

on:
  push:
    paths:
      - src/Services/Payment/**.cs
      - src/Services/Payment/**.csproj
      - Directory.Build.props
      - .github/workflows/payment.yaml

jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      project: src/Services/Payment
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests