name: Shopping Cart - Command
run-name: Shopping Cart Command Workflow
on:
  push:
    paths:
      - src/Services/ShoppingCart/Command/**.cs
      - src/Services/ShoppingCart/Command/**.csproj
      - Directory.Build.props
      - .github/workflows/shopping-cart-command.yaml
jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/ShoppingCart/Command
      project: WorkerService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests  