name: Warehouse - Command
run-name: Warehouse Command Workflow
on:
  push:
    paths:
      - src/Services/Warehouse/Command/**.cs
      - src/Services/Warehouse/Command/**.csproj
      - Directory.Build.props
      - .github/workflows/warehouse-command.yaml
jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/Warehouse/Command
      project: WorkerService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests  