name: Warehouse - Query
run-name: Warehouse Query Workflow
on:
  push:
    paths:
      - src/Services/Warehouse/Query/**.cs
      - src/Services/Warehouse/Query/**.csproj
      - Directory.Build.props
      - .github/workflows/warehouse-query.yaml
jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: src/Services/Warehouse/Query
      project: GrpcService
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests