name: Warehouse

on:
  push:
    paths:
      - src/Services/Warehouse/**.cs
      - src/Services/Warehouse/**.csproj
      - Directory.Build.props
      - .github/workflows/warehouse.yaml

jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      project: src/Services/Warehouse
      test: test/Web/WebAPI/ECommerce.WebAPI.IntegrationTests